travis:
  secure:
    BINSTAR_TOKEN: XmeBpDHzQGL6qj0GcaRrW7rNuepSWN8PM/q3s/9gDtcZhmuyQJ1xQTY1+dFw+81A+w8xw15iJPafzck4Dp/MPSWvCfBjUIBHasU47tYykjaDH3LKj+x/ktMpwAOO+tax5o0iiVEk95TxQv1LM83WYfrEq5Tsbm+Xigu2pSn7v4zOAGqw7KpBLpoXmIQD2yc+tds5RdUQjlZwLyV7LS5BNMo8+j/MKjP2MO4fw3VfysPY5orwFH9+Zka6A3/dQe1frKYunTBqmrZgngy5nDSLKIA/83L4LsYjSklHnHAVB7Po/kjEnXh4mGcksELX3sAKGfDbV9q023z2kSsatSRHVjkllnqlLb9dBV3LVIvxMOp1vlxw263kDYeS0kd3DWywBzNojCk1UFDcikiV1F9NpZtVK9fu74El0DQPDa8BzUVty/qC71KqCaJdYWTpHBLpnpA4xpmLktXk+uETUzGZYkrj13Je1JHCx1GRCdVbLw/pLi1bJ20AMz6W/p7XF+oiQS3R0/EzglfVUSirYAKiEsHKVY3IhGcJq13h9jmAS0bhbVAUbjsWfLBM6X3oAL2JXHTFjtk1UF9FBeXyRgLCjGllkJ1pV341izH31jgfdf3YPH4Q7n6Vb3r+tr7mxqzm5hCGzwwvxlBgJEySUjlFYdG0+45RvC2J3YuSLadiduY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
